version: "3.3"

services:

    auth_app:
        build:
            context: ./app
            dockerfile: Dockerfile

        ports:
            - "80:80"

        volumes:
            - ./app:/var/www/html/app
